Update Android.yml

diff --git a/.github/workflows/Android.yml b/.github/workflows/Android.yml
--- a/.github/workflows/Android.yml
+++ b/.github/workflows/Android.yml
@@ -17,11 +17,6 @@ jobs:
       - name: Checkout source code
         uses: actions/checkout@v4
 
-      - name: Setup Gradle
-        uses: gradle/gradle-build-action@v3
-        with:
-          gradle-version: 8.0
-
       - name: Set up JDK 17
         uses: actions/setup-java@v4
         with:
@@ -46,7 +41,10 @@ jobs:
 
       - name: Create Gradle Wrapper
         run: |
-          ./gradlew wrapper --gradle-version 8.0 --distribution-type bin
+          # Hanya generate wrapper jika belum ada
+          if [ ! -f "gradlew" ]; then
+            gradle wrapper --gradle-version 8.0 --distribution-type bin
+          fi
           chmod +x gradlew
           chmod -R 755 gradle
 
@@ -58,6 +56,10 @@ jobs:
         run: |
           echo "Searching for APK..."
           apk_path=$(find app/build/outputs/apk/debug -name "*.apk" | head -n 1)
+          if [ -z "$apk_path" ]; then
+            echo "APK not found!"
+            exit 1
+          fi
           echo "debug_apk=$apk_path" >> $GITHUB_OUTPUT
 
       - name: Upload Debug APK
